---
- name: App Server
  hosts: web
  sudo: yes
  user: root
  gather_facts: False

  roles:
    - common
    - firewall
    - ruby
    - nginx
    - unicorn
    - upstart
    - monit
    - postgresql

# Use this block to send a message to an IRC channel
#- name: Alert we are done
#  hosts: notify
#  tasks:
#    - irc: >
#        server=irc.freenode.net
#        channel="#channel"
#        msg="All finished ."
#        color=red
#        nick=ansibleAlert

# Use this block to a different node
#- name: Database Server
#  hosts: db
#  sudo: yes
#  user: root
#
#  roles:
#    - common
#    - postgresql
